### ISSUE TITLE
Bulk insert limit

### ISSUE THREAD

**Issue by pchrzasz** [Azure/azure-documentdb-java#105]
Hello,

II would like to ask you about bulk insert limits in CosmosDB. I have noticed that I can only do 800 rows in a bulk insert (capacity set to 10000RU). Over this limit e.g. 1000 rows there are errors:

`Apr 08, 2018 12:04:37 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Got more than one input Future failure. Logging failures after the first
java.lang.RuntimeException: pki 0 Failed to import mini-batch. Exception was Unrecognized field "failedDoc" (class com.microsoft.azure.documentdb.bulkimport.BulkImportStoredProcedureResponse), not marked as ignorable (2 known properties: "errorCode", "count"])
at [Source: (String)"{"count":819,"errorCode":0,"failedDoc":null}"; line: 1, column: 44] (through reference chain: com.microsoft.azure.documentdb.bulkimport.BulkImportStoredProcedureResponse["failedDoc"])
	at com.microsoft.azure.documentdb.bulkimport.BatchInserter$1.call(BatchInserter.java:239)
	at com.microsoft.azure.documentdb.bulkimport.BatchInserter$1.call(BatchInserter.java:134)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "failedDoc" (class com.microsoft.azure.documentdb.bulkimport.BulkImportStoredProcedureResponse), not marked as ignorable (2 known properties: "errorCode", "count"])`

Insert one by one successfully finished, so this is not a problem with my data. Therefore I suppose that you have some limits which I have not found on your site.

**Comment by tknandu** [comment]
@pchrzasz We have moved the bulk import functionality into an extension library [here](https://github.com/Azure/azure-cosmosdb-bulkexecutor-java-getting-started)
