### ISSUE TITLE
Getting error "Date header doesn't conform to the required format..."

### ISSUE THREAD

**Issue by dixitprashant444** [Azure/azure-documentdb-java#115]
I tried using following SDK:
http://search.maven.org/#artifactdetails|com.microsoft.azure|azure-documentdb|1.16.1|jar
However, while reading/writing a record, I get following exception:

Caused by: com.microsoft.azure.documentdb.DocumentClientException: Message: {"Errors":["Date header doesn't conform to the required format. Please ensure that the time is provided in GMT and conforms to RFC 1123 date-time specifications.","Date header doesn't conform to the required format. Please ensure that the time is provided in GMT and conforms to RFC 1123 date-time specifications."]}
ActivityId: 1643bc3e-66ad-4d94-a10a-87a02508aaab, Request URI: /apps/9efe5cf7-bad6-4171-9853-10018182fcd9/services/9eb04a76-92a1-452c-abb7-5f82b2152b06/partitions/6455b477-7aba-4d87-854b-d98cfe93c8b0/replicas/131713572097493822s, RequestStats:
ResponseTime: 2018-05-31T10:17:36.0939044Z, StoreReadResult: StorePhysicalAddress: rntbd://10.0.0.74:14000/apps/9efe5cf7-bad6-4171-9853-10018182fcd9/services/9eb04a76-92a1-452c-abb7-5f82b2152b06/partitions/6455b477-7aba-4d87-854b-d98cfe93c8b0/replicas/131713572097493823s, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 0, IsGone: True, IsNotFound: False, IsInvalidPartition: False, RequestCharge: 0, ItemLSN: -1, ResourceType: Document, OperationType: ReadFeed
ResponseTime: 2018-05-31T10:17:36.0939044Z, StoreReadResult: StorePhysicalAddress: rntbd://10.0.0.180:14000/apps/9efe5cf7-bad6-4171-9853-10018182fcd9/services/9eb04a76-92a1-452c-abb7-5f82b2152b06/partitions/6455b477-7aba-4d87-854b-d98cfe93c8b0/replicas/131713572097493822s, LSN: 27, GlobalCommittedLsn: 26, PartitionKeyRangeId: , IsValid: True, StatusCode: 0, IsGone: False, IsNotFound: False, IsInvalidPartition: False, RequestCharge: 0, ItemLSN: -1, ResourceType: Document, OperationType: ReadFeed
, SDK: Microsoft.Azure.Documents.Common/2.0.0.0, StatusCode: Unauthorized
        at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:74)
        at com.microsoft.azure.documentdb.internal.GatewayProxy.performGetRequest(GatewayProxy.java:253)
        at com.microsoft.azure.documentdb.internal.GatewayProxy.doReadFeed(GatewayProxy.java:113)
        at com.microsoft.azure.documentdb.internal.GatewayProxy.processMessage(GatewayProxy.java:366)
        at com.microsoft.azure.documentdb.DocumentClient$9.apply(DocumentClient.java:3063)
        at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:61)
        at com.microsoft.azure.documentdb.DocumentClient.doReadFeed(DocumentClient.java:3073)
        at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doReadFeed(DocumentQueryClientInternal.java:36)
        at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:220)
        at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:135)
        at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:98)
        at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:81)
        ... 138 common frames omitted

Sample JSON used:

{
  "type": "FIRMWARE",
  "softwareId": "string",
  "softwareReleaseId": "string",
  "softwareVersion": "string",
  "customData": {},
  "artifacts": [
    {
      "uri": "string",
      "checksum": "string",
      "name": "string",
      "validUntil": "2018-06-04T09:45:49.487Z"
    }
  ],
  "transitions": [
    {
      "from": "CREATED",
      "to": "CREATED",
      "type": "BACKEND_TRIGGER",
      "details": {}
    }
  ]
}

"validUntil": "2018-06-04T09:45:49.487Z" is creating issue.
Java code sample of this field:
@JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
private Date validUntil;

Then I tried  with 1.15.2 version for the same SDK & it works fine. Is this a regression in new version? Shall we use version 1.15.2 instead of 1.16.1?

**Comment by moderakh** [comment]
working with @dixitprashant444 offline. @dixitprashant444 as discussed in the email offline please send the simple project reproducing this.

**Comment by dixitprashant444** [comment]
I created a sample spring boot application which is quite similar to our actual application.
However, I could not reproduce the issue as it works fine.
Not sure if any other Spring library conflicts & causes this issue. I am trying to find it out.

**Comment by dixitprashant444** [comment]
I was able to reproduce this issue. 
Till version 1.15.2 of document db SDK, current date-time in GMT format (requited for x-ms-date header in DocumentClient.class of SDK) was calculated using SimpleDateFormat class of Java. However, with version 1.16.1 of document db SDK, they have started using joda-time:2.9.9 to calculate current date-time in GMT format.
If any client application, which is using 1.16.1 SDK, already has lower version (<=2.7) of joda-time dependency then this issue occurs. To resolve this issue, one needs to either use lower version (1.15.2) of document db SDK or upgrade joda-time dependency to version 2.9.9 inside his/her application.
However, I still feel that better solution would be to remove joda-time dependency and use SimpleDateFormat class of Java. I hope that the document db SDK owners would consider this when they release a new version.
