### ISSUE TITLE
bulk import throws BulkImportStoredProcedureResponse exception

### ISSUE THREAD

**Issue by ytaous** [Azure/azure-documentdb-java#117]
Hi, when we use the importer (v.1.16.0), it always throws the exception. I noticed there's change log has that option to disable the exception. Is it accidental removed? Can we add it back? 

## Changes in 1.9.4 : ##
- Set FAIL_ON_UNKNOWN_PROPERTIES = false so users don't need to define JsonIgnoreProperties in their POJO.

com.microsoft.azure.documentdb.bulkexecutor.bulkimport.BulkImportStoredProcedureResponse), not marked as ignorable (2 known properties: "errorCode", "count"])
at [Source: {"count":2,"errorCode":0,"failedDoc":null}; line: 1, column: 42] (through reference chain: com.microsoft.azure.documentdb.bulkexecutor.bulkimport.BulkImportStoredProcedureResponse["failedDoc"])
              at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
              at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
              at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
              at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
              at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
              at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
              at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
              at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
              at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
              at com.microsoft.azure.documentdb.bulkexecutor.bulkimport.BatchInserter.parseFrom(BatchInserter.java:259)
              at com.microsoft.azure.documentdb.bulkexecutor.bulkimport.BatchInserter.access$1100(BatchInserter.java:54)
              at com.microsoft.azure.documentdb.bulkexecutor.bulkimport.BatchInserter$1.call(BatchInserter.java:159)
              at com.microsoft.azure.documentdb.bulkexecutor.bulkimport.BatchInserter$1.call(BatchInserter.java:117)

**Comment by ytaous** [comment]
bulk executor has the missing field, so I am closing it
