### ISSUE TITLE
When using Resource Tokens java.util.concurrent.ExecutionExceptions being logged

### ISSUE THREAD

**Issue by marc-sensenich** [Azure/azure-documentdb-java#126]
When using version `v2.2.1` `java.util.concurrent.ExecutionException: java.lang.NullPointerException` are being logged when calling `documentClient.createDocument()`as an example call when a `DocumentClient` is granted authrorization using resource tokens with the `All` permission mode given for a collection. After debugging, it seems that these exceptions are due to the method `getAuthorizationTokenUsingResourceTokens` from the class `BaseAuthorizationTokenProvider` not returning a resource token when being used in a call to `getPartitionKeyRangeById` in the method `setSessionToken` from the class `SessionContainer`. This would be due to the permission being created using the IDs for the database and collection that are defined by the administrator, but the method `getPartitionKeyRangeById` using `DocumentCollection.getSelfLink()`

## Example code to reproduce the issue

```java
public class GithubIssue {
  // Replace with your DocumentDB end point
  private static final String END_POINT = "";
  // Define an id for your database and collection
  private static final String DATABASE_ID = "TestDB";
  private static final String COLLECTION_ID = "TestCollection";

  // Replace this with a JSON string with the 'All' permission to the collection within the database being tested
  private static final String PERMISSION = "{\n" +
      "    \"id\": \"a_permission\",  \n" +
      "    \"permissionMode\": \"Read\",  \n" +
      "    \"resource\": \"dbs/volcanodb/colls/volcano1\",  \n" +
      "    \"_rid\": \"Sl8fAG8cXgBn6Ju2GqNsAA==\",  \n" +
      "    \"_ts\": 1449604760,  \n" +
      "    \"_self\": \"dbs\\/Sl8fAA==\\/users\\/Sl8fAG8cXgA=\\/permissions\\/Sl8fAG8cXgBn6Ju2GqNsAA==\\/\",  \n" +
      "    \"_etag\": \"\\\"00000e00-0000-0000-0000-566736980000\\\"\",  \n" +
      "    \"_token\": \"type=resource&ver=1&sig=ocPyc9QQFybITu1EqzX0kg==;w+WR1aWafB3+yZq5JSoBwgz78XDlU+k9Xiqvc+Q7TlAl1P4h4t721Cn5cjhZ9h3TSd2\\/MJLy+wG+YkhDL9UlGkVv05RZGy2fMaLGdeQkWc7TShkc\\/M2boPc3GXq2yiERKl5CN4AZWSOcrFhOFuuTOqF4ZdBlflmNudaakodr\\/8qTip0i+a7moz1Jkc5+9iLAsDFyqTR1sirp7kAVNFbiqPdYTjNkvZUHF3nYYmRskOg=;\"  \n" +
      "}";

  // We'll use Gson for POJO <=> JSON serialization for this sample.
  // Codehaus' Jackson is another great POJO <=> JSON serializer.
  private static Gson gson = new Gson();
  public static void main(String[] args) throws DocumentClientException,
      IOException {
    JsonElement element = new JsonParser().parse(PERMISSION);
    List<Permission> permissions = new ArrayList<>();
    permissions.add(new Permission(element.toString()));

    // Instantiate a DocumentClient w/ your DocumentDB Endpoint and Permissions
    DocumentClient documentClient = new DocumentClient(END_POINT,
        permissions, ConnectionPolicy.GetDefault(),
        ConsistencyLevel.Strong);

    // Create an object, serialize it into JSON, and wrap it into a
    // document.
    SomePojo allenPojo = new SomePojo("123", "Allen Brewer", "allen [at] contoso.com");
    String allenJson = gson.toJson(allenPojo);
    Document allenDocument = new Document(allenJson);

    // Create the 1st document.
    allenDocument = documentClient.createDocument(
        "dbs/" + DATABASE_ID + "/colls/" + COLLECTION_ID, allenDocument, null, false)
        .getResource();

    System.out.println(allenDocument.toString());
  }
}
```

## Example stacktrace and logs

```log
Try looking up routing map for collection dbs/system-generated-db-id/colls/system-generated-coll-id/, obsoleteValue: null stack {}
Add cache [dbs/system-generated-db-id/colls/system-generated-coll-id/], obsoleteValue: null
Querying PartitionKeyRange change feed. collectionLink: [dbs/system-generated-db-id/colls/system-generated-coll-id/]
'Linux' with 'amd64' system is not compatible with native library. JNI not loaded.
ExecutionException while trying to look up CollectionRoutingMap
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.tryLookUp(PartitionKeyRangeCache.java:76)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getPartitionKeyRangeById(PartitionKeyRangeCache.java:99)
	at com.microsoft.azure.documentdb.internal.SessionContainer.setSessionToken(SessionContainer.java:346)
	at com.microsoft.azure.documentdb.internal.SessionTokenHelper.captureSessionToken(SessionTokenHelper.java:137)
	at com.microsoft.azure.documentdb.DocumentClient.captureSessionToken(DocumentClient.java:3228)
	at com.microsoft.azure.documentdb.DocumentClient.doCreate(DocumentClient.java:3026)
	at com.microsoft.azure.documentdb.DocumentClient.access$100(DocumentClient.java:85)
	at com.microsoft.azure.documentdb.DocumentClient$1.apply(DocumentClient.java:850)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeCreateDocument(RetryUtility.java:184)
	at com.microsoft.azure.documentdb.DocumentClient.createDocument(DocumentClient.java:855)
	at GithubIssue.main(GithubIssue.java:98)
Caused by: java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.microsoft.azure.documentdb.DocumentClient.putMoreContentIntoDocumentServiceRequest(DocumentClient.java:3458)
	at com.microsoft.azure.documentdb.DocumentClient.doReadFeed(DocumentClient.java:3115)
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doReadFeed(DocumentQueryClientInternal.java:43)
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:220)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:136)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:99)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.hasNext(DefaultQueryExecutionContext.java:71)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:67)
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:23)
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:70)
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:115)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:57)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:31)
	at com.microsoft.azure.documentdb.DocumentClient.queryChangeFeed(DocumentClient.java:1291)
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.readPartitionKeyRangesChangeFeed(DocumentQueryClientInternal.java:33)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getRoutingMapForCollection(PartitionKeyRangeCache.java:133)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.access$000(PartitionKeyRangeCache.java:29)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:72)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by simplynaveen20** [comment]
This is the issue in sync java SDK  , we would recommend to use async java SDK where this thing is working fine without exception , and also which is more robust and up to date.

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-async-java

 And if that is not an option  could we please use collection self link in the permission json and also while creating document like below

private static final String PERMISSION = "{\n" +
"  \"id\": \"TestPermission\",\n" +
"  \"permissionMode\": \"ALL\",\n" +
"  \"resource\": \"dbs/1VleAA==/colls/1VleAP3Cjjc=/\",\n" +
"  \"_rid\": \"1VleAGCiTQC7WjVeBO0CAA==\",\n" +
"  \"_self\": \"dbs/1VleAA==/users/1VleAGCiTQA=/permissions/1VleAGCiTQC7WjVeBO0CAA==/\",\n" +
"  \"_etag\": \"\\\"00000000-0000-0000-a9cd-8afd46ed01d4\\\"\",\n" +
"  \"_token\": \"type=resource&ver=1&sig=SM+2QBNR99M+t55gWtx0AQ==;PJP/fZ7Rs+PQ/p2862IpJPIYh7J5C8xho3g40CU6shw0RKwGWOMfrZ6XSEKyB85dMTnHxLQARP/zvGneACeFF9xLpH3+SXJqtiVa5wxCU/Jrcu9liLq" +
"+ejSPosH1qyzlBuUDL15FJfxljeedLqYpxzq+R+Fw6Xbq88OF7502cFbEs696sR5tli4dvt918IC9xXH3eQGj7KCq3Pvg3HC9bpMRRlK8195gbxDdwyXV6hiPn9F7M7X3qrFSiQxny8NS;\",\n" +
"  \"_ts\": 1547225336\n" +
"}\n";

 

                    
// Create the 1st document.
allenDocument = documentClient.createDocument(
"dbs/1VleAA==/colls/1VleAP3Cjjc=/", allenDocument, null, false)
    .getResource();

**Comment by marc-sensenich** [comment]
Thank you for the update @simplynaveen20. We tried the Async client yesterday and encountered the following issue https://github.com/Azure/azure-cosmosdb-java/issues/78 unrelated to this one

**Comment by simplynaveen20** [comment]
Thank you Marc.
Lets follow up on Azure/azure-cosmosdb-java#78 , I put some comment over there

**Comment by sergeig-stcu** [comment]
I've got a similar issue:

```
TRACE 2019-08-09 14:03:59,355 [pool-18-thread-1] [event: ] com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache: Getting routing map for collection dbs/+1NQAA==/colls/+1NQAM04RDc=/
DEBUG 2019-08-09 14:03:59,355 [pool-18-thread-1] [event: ] com.microsoft.azure.documentdb.DocumentClient: Querying PartitionKeyRange change feed. collectionLink: [dbs/+1NQAA==/colls/+1NQAM04RDc=/]
ERROR 2019-08-09 14:03:59,355 [pool-18-thread-1] [event: ] com.microsoft.azure.documentdb.DocumentClient$DocumentDBThreadPoolExecutor: Runnable execution exception
java.lang.NullPointerException: null
	at java.net.URLEncoder.encode(URLEncoder.java:204) ~[?:1.8.0_212]
	at com.microsoft.azure.documentdb.DocumentClient.putMoreContentIntoDocumentServiceRequest(DocumentClient.java:3465) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentClient.doReadFeed(DocumentClient.java:3122) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doReadFeed(DocumentQueryClientInternal.java:43) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:220) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:136) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:99) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.hasNext(DefaultQueryExecutionContext.java:71) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:67) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:23) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:70) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:115) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:57) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:31) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentClient.queryChangeFeed(DocumentClient.java:1291) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.readPartitionKeyRangesChangeFeed(DocumentQueryClientInternal.java:33) ~[?:?]
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getRoutingMapForCollection(PartitionKeyRangeCache.java:133) ~[?:?]
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.access$000(PartitionKeyRangeCache.java:29) ~[?:?]
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:72) ~[?:?]
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:69) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
WARN  2019-08-09 14:03:59,355 [[MuleRuntime].io.05: [ebiz-member-event-history-api].implementationFlow.BLOCKING @596c2cf8] [event: 2e8c6550-bae9-11e9-b5a0-02154a582b65] com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache: ExecutionException while trying to look up CollectionRoutingMap
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.tryLookUp(PartitionKeyRangeCache.java:76) ~[?:?]
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getPartitionKeyRangeById(PartitionKeyRangeCache.java:99) ~[?:?]
	at com.microsoft.azure.documentdb.internal.SessionContainer.setSessionToken(SessionContainer.java:350) ~[?:?]
	at com.microsoft.azure.documentdb.internal.SessionTokenHelper.captureSessionToken(SessionTokenHelper.java:137) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentClient.captureSessionToken(DocumentClient.java:3235) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentClient.doQuery(DocumentClient.java:3145) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doQuery(DocumentQueryClientInternal.java:47) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:219) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:159) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:99) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.hasNext(DefaultQueryExecutionContext.java:71) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:67) ~[?:?]
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:23) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:70) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:115) ~[?:?]
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:57) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:1167) ~[?:?]
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:1138) ~[?:?]
```

I use a read only resource token with code like this:

```java
permFeed is set to list with one resource permission object
docClient = new DocumentClient(cosmosUrl, permFeed, connectionPolicy, ConsistencyLevel.Session);

curPage = new ArrayList<Map<String, Object>>();
queryOptions = new FeedOptions();
queryOptions.setEnableCrossPartitionQuery(true); // does not seem to make a difference
queryResults = docClient.queryDocuments(collectionLink, query, queryOptions);
if (queryResults != null) {
    curDocs = queryResults.getQueryIterable().fetchNextBlock();
}
```
