### ISSUE TITLE
Update using PoJo setters result in a "NullPointerException"

### ISSUE THREAD

**Issue by boly38** [Azure/azure-documentdb-java#24]
Hi
the todo tutorial show an "updateTodo" sample with the following comment:

    // You can update the document as a JSON document directly.
    // For more complex operations - you could de-serialize the document in
    // to a POJO, update the POJO, and then re-serialize the POJO back in to
    // a document.

I want to update my pojo using the java object (not the documentdb "Document" setters)
When I do that, 

        Document myDoc = getDocumentById(myId);
        // De-serialize the document in to a TodoItem.
        MyObject my = gson.fromJson(myDoc .toString(), MyObject.class);
        LOG.debug("update object {}", my);
        my.setName("IWantToUsePojoPlease");
        Document updDocument = new Document(gson.toJson(my));
        updDocument.setResourceId(myDoc.getResourceId());
        updDocument.setId(myDoc.getId());
        updDocument.set("entityType", ENTITY_TYPE);
        try {
            // Persist/replace the updated document.
            updDocument = getDC().replaceDocument(updDocument, null).getResource();

I got the following error:

    java.lang.NullPointerException
    at com.microsoft.azure.documentdb.DocumentClient.trimBeginingAndEndingSlashes(DocumentClient.java:2160)
    at com.microsoft.azure.documentdb.DocumentClient.joinPath(DocumentClient.java:2148)
    at com.microsoft.azure.documentdb.DocumentClient.replaceDocument(DocumentClient.java:503)

I think this is a bug. Maybe the new Document instance loose the "_self"(SELF_LINK) reference and that's why the replace doesn't work. How could we keep this link ? Is it possible to fix this issue and add a second update sample using PoJo ?

If possible, I would like to avoid an update that will use Document.set(FIELD,VALUE) method but use PoJo (business) setters.

Regards

**Comment by aliuy** [comment]
Thank you; I believe you are right that this is a bug. The _self property can get lost when deserializing to a POJO (because there isn't an object attribute to hold the value).

For an interim solution - you can add a _self property to your POJO.

For a longer term solution - I will investigate adding document system properties (e.g. _self) in to a common class (e.g. com.microsoft.azure.documentdb.Document) that POJOs can extend from. System properties currently get stored in a JSONObject (propertyBag) in JSONSerialiable and as a result, can get lost when a deserializing to a POJO.

**Comment by boly38** [comment]
@aliuy Hi,
Just to confirm that using your workaround, you could use PoJo setters

If My PoJo `User` embed a **`_self`** String attribute, then the following `update()` method will work:

    @Override
    public User update(User u) {
        Document usrDoc = getDocumentById(u.getId());
        LOG.debug("ORIGINAL SELF:{}", usrDoc.getSelfLink());
        if (usrDoc == null) {
            return null;
        }
        // De-serialize the document in to a User.
        User byId = jsonSvc.fromJson(usrDoc.toString(), User.class);
        byId.setId(u.getId());
        byId.setName(u.getName());
        byId.setMyComplexField(u.getMyComplexField());

        Document updDocument = new Document(jsonSvc.toJson(byId));
        updDocument.set("entityType", ENTITY_TYPE);
        LOG.debug("UPD SELF:{}", updDocument.getSelfLink());
        
        try {
            // Persist/replace the updated document.
            updDocument = getDC().replaceDocument(updDocument, null).getResource();
        } catch (DocumentClientException e) {
            LOG.error("Unable to update User entity : " + e.getMessage(), e);
            return null;
        }
        modified();
        LOG.debug("update {}", byId);
        return byId;
    }

thx!

**Comment by aqua-regia** [comment]
I don't think this is a bug. If your class in which you are deserializing your JSON contains getters and setters for _self and has _self property then this will work.
	@SerializedName("_self")
	@Expose
	private String _self;


 The other way can be that during the update you should set the field (_rid, _self, _etag, _attachments, _ts) before calling the update method. 

but the thing is that while inserting it automatically assigns these properties but while updating the documents it expects you to pass them. 

I delete the document and then reinsert it instead of update.
