### ISSUE TITLE
Can't use id-based urls with TOP and Partitioned Collection

### ISSUE THREAD

**Issue by itszakko** [Azure/azure-documentdb-java#68]
Hello Everyone,
I am trying to use the [newer style id-based resource links](https://azure.microsoft.com/en-us/blog/azure-documentdb-bids-fond-farewell-to-self-links/) with TOP in the query and a partitioned collection.

Here's the line that fails:
```java
List<Document> documents =
        client.queryDocuments("dbs/foo/colls/test",
                              "SELECT TOP 10 * FROM c", options)
              .getQueryIterable().toList();
```

If the string in queryDocuments is a selfLink uri or the collection is *not* partitioned, the above code works fine.

Here's the full exception.
```
Connected to the target VM, address: '127.0.0.1:56839', transport: 'socket'
Feb 20, 2017 7:29:26 PM com.microsoft.azure.documentdb.internal.ServiceJNIWrapper initializeServiceJni
WARNING: 'Mac OS X' with 'x86_64' system is not compatible with native library. JNI not loaded.
Exception in thread "main" java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Server could not parse the Url., StatusCode: NotFound
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getOverlappingRanges(PartitionKeyRangeCache.java:34)
	at com.microsoft.azure.documentdb.internal.routing.RoutingMapProviderHelper.getOverlappingRanges(RoutingMapProviderHelper.java:58)
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.getTargetPartitionKeyRanges(AbstractQueryExecutionContext.java:71)
	at com.microsoft.azure.documentdb.internal.query.ParallelQueryExecutionContext.<init>(ParallelQueryExecutionContext.java:55)
	at com.microsoft.azure.documentdb.internal.query.PipelinedQueryExecutionContext.<init>(PipelinedQueryExecutionContext.java:14)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:83)
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:20)
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:68)
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:113)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:55)
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:969)
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:929)
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:908)
	at Main.main(Main.java:28)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Server could not parse the Url., StatusCode: NotFound
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getOverlappingRanges(PartitionKeyRangeCache.java:32)
	... 13 more
Caused by: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Server could not parse the Url., StatusCode: NotFound
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:53)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:10)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:68)
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:20)
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:68)
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:113)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:55)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:29)
	at com.microsoft.azure.documentdb.DocumentClient.readPartitionKeyRanges(DocumentClient.java:1430)
	at com.microsoft.azure.documentdb.DocumentQueryClient.readPartitionKeyRanges(DocumentQueryClient.java:28)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getRoutingMapForCollection(PartitionKeyRangeCache.java:72)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.access$000(PartitionKeyRangeCache.java:12)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:30)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.documentdb.DocumentClientException: Server could not parse the Url., StatusCode: NotFound
	at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:68)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.performGetRequest(GatewayProxy.java:224)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.doReadFeed(GatewayProxy.java:104)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.processMessage(GatewayProxy.java:313)
	at com.microsoft.azure.documentdb.DocumentClient$9.apply(DocumentClient.java:2631)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:54)
	at com.microsoft.azure.documentdb.DocumentClient.doReadFeed(DocumentClient.java:2638)
	at com.microsoft.azure.documentdb.DocumentQueryClient.doReadFeed(DocumentQueryClient.java:32)
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:185)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:78)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:66)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:51)
	... 17 more
```

**Comment by moderakh** [comment]
@ubercow thanks for reporting this.

Could you please let us know which version of azure documentdb jar you are using?

**Comment by ubercow** [comment]
Yes I am currently using 1.9.5 off of Maven, though the issue also seems to affect 1.9.4

**Comment by moderakh** [comment]
@ubercow I am trying to reproduce the problem locally, but it just works for me!

Could you please share your code in a small java prog?

Also does this fail for you all the time? or does it fail randomly?

**Comment by ubercow** [comment]
@moderakh 
Here you go:
https://gist.github.com/ubercow/20925ac8d745cb0184ef8773b4e9e55a

The important part here is the settings on the collection itself.
![image](https://cloud.githubusercontent.com/assets/68832/23183938/9cf53dea-f832-11e6-9dd5-376ae384a5d9.png)

Notably, that it's sharded.

**Comment by moderakh** [comment]
@ubercow thanks for the code.

I tested your code against a partition collection and just worked for me!

I couldn't reproduce the problem. A few questions for you:

1. What happens if you create a new partitioned collection and test against that new collection?
2. This sounds trivial but could it be that you are copying and pasting the collection name or database name and some unwanted characters gets in your code?
3. What's the throughput associated with your partitioned collection?

**Comment by ubercow** [comment]
A new instance works for me as well with the same code. I'm beginning to think this is not an issue with the library, but an issue with my specific DocumentDb instance itself.

When I tried a new instance, it worked. However any collection I create on this current failing instance seems to fail with the same exception. It's not a copypaste issue, because when I remove the `TOP 10` part from the query it works fine.

It's not ideal, but I'm just going to recreate the instance and hope it continues working there. If not I suppose I'll open a ticket with Azure support.

If you think there's something you can do from inside of MSFT, I'd be happy to email subscription information to a MSFT email. If not, I'm closing this. Thanks for all your help either way 😃

**Comment by moderakh** [comment]
@ubercow this definitely has to work for all instances. Someone from our backend team will be in contact with you soon to troubleshoot the problem in your specific DocumentDB instance.

**Comment by moderakh** [comment]
@ubercow could you please try to reproduce this on your side and give us the activityId for the failure?

**Comment by ubercow** [comment]
I extended my sample code (super hacky!) to dump headers

```
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000
Server: Microsoft-HTTPAPI/2.0
x-ms-gatewayversion: version=1.11.150.2
x-ms-activity-id: d5cb849b-0c01-4f6a-9859-6454b1f1e91a
Date: Thu, 23 Feb 2017 09:37:50 GMT
Content-Type: application/json
```

and here's the code I used to dump it.
https://gist.github.com/ubercow/20925ac8d745cb0184ef8773b4e9e55a#file-reproduction_headers-java

**Comment by Blackbaud-RajRaulji** [comment]
Is there any new information this?

**Comment by itszakko** [comment]
This was an issue with my specific documentdb instance. I resolved it with Azure Support.
