### ISSUE TITLE
PoolingClientConnectionManager not working in Android studio

### ISSUE THREAD

**Issue by Souvik04** [Azure/azure-documentdb-java#94]
Hi,

I am trying to connect to Azure Cosmos DB through my Android application. I have followed the quick start link for Java in Azure portal and this link- https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-java-application.

When I try to create the `DocumentClient` it fails.

`DocumentClient documentClient = new DocumentClient(HOST, MASTER_KEY, ConnectionPolicy.GetDefault(), ConsistencyLevel.Session);`

I debugged this in API 23, 25 and 27. They all fail with some error. The closest I have come across is that it fails at this point-

`this.connectionManager = new PoolingClientConnectionManager(SchemeRegistryFactory.createDefault()); //for API 23`

I updated all the dependency packages to latest version but it fails somewhere around while creating the `PoolingClientConnectionManager`.

I have posted this issue to Stackoverflow- https://stackoverflow.com/questions/47572115/unable-to-create-documentclient-for-azure-cosmos-db but got no response, so thought of looking here.

Is there any workaround or resolution for this preferably in Android API 23?

Thanks,
Souvik

**Comment by moderakh** [comment]
@Souvik04 please give us the stacktrace. What fails?

**Comment by Souvik04** [comment]
@moderakh Here is the stack trace from Android studio-

` --------- beginning of crash
12-06 06:50:33.096 3521-3521/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: is.lagerinn.teztrating, PID: 3521
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/conn/PoolingClientConnectionManager;
                                                     at com.microsoft.azure.documentdb.GatewayProxy.<init>(GatewayProxy.java:82)
                                                     at com.microsoft.azure.documentdb.DocumentClient.initialize(DocumentClient.java:137)
                                                     at com.microsoft.azure.documentdb.DocumentClient.<init>(DocumentClient.java:75)
                                                     at is.lagerinn.teztrating.RatingActivity.onCreate(RatingActivity.java:48)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.conn.PoolingClientConnectionManager" on path: DexPathList[[zip file "/data/app/is.lagerinn.teztrating-1/base.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_dependencies_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_0_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_1_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_2_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_3_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_4_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_5_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_6_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_7_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_8_apk.apk", zip file "/data/app/is.lagerinn.teztrating-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/is.lagerinn.teztrating-1/lib/x86, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.microsoft.azure.documentdb.GatewayProxy.<init>(GatewayProxy.java:82) 
                                                     at com.microsoft.azure.documentdb.DocumentClient.initialize(DocumentClient.java:137) 
                                                     at com.microsoft.azure.documentdb.DocumentClient.<init>(DocumentClient.java:75) 
                                                     at is.lagerinn.teztrating.RatingActivity.onCreate(RatingActivity.java:48) 
                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                 	Suppressed: java.lang.ClassNotFoundException: org.apache.http.impl.conn.PoolingClientConnectionManager
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 17 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by moderakh** [comment]
@Souvik04 you are getting this error due to a dependency conflict on apache http client.

You need to make sure you have the following jars in your class path:
org.apache.httpcomponents » httpcore:4.4.6
org.apache.httpcomponents » httpclient:4.5.2

Also you need to make sure you are not bringing older version of these libraries.

**Comment by moderakh** [comment]
closing this as this is due to not bringing in the right dependencies. If you face issues feel free to create a new issue.
